spring.application.name=productInventory

# MongoDB URI completa
spring.data.mongodb.uri=mongodb+srv://dbProductInventoryU:Product1013@cluster0.heuldna.mongodb.net/productInventoryDB

# Excluir configuración JDBC
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Puerto del servidor Spring Boot
server.port=8086


